trigger: none
pr: none

schedules:
  - cron: "0 9 * * Mon-Fri"
    displayName: Weekdays at 9:00 UTC
    branches:
      include:
        - main

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: generateNotice
    displayName: 📝 Generate Notice
    type: boolean
    default: true
  - name: publishExtension
    displayName: 🚀 Publish Pre-Release
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/pre-release.yml@templates
  parameters:
    publishExtension: ${{ parameters.publishExtension }}
    generateNotice: ${{ parameters.generateNotice }}
    ghCreateTag: true
    standardizedVersioning: true
    nodeVersion: 22.x

    buildSteps:
      - task: NodeTool@0
        inputs:
          versionSpec: 22.x
        displayName: Install Node.js

      - script: npm ci --ignore-scripts
        displayName: Install root dependencies

      - script: npm ci
        displayName: Install extension dependencies
        workingDirectory: vscode-extension

      - script: npm run build
        displayName: Build CLI

      - script: node esbuild.mjs --production
        displayName: Build extension
        workingDirectory: vscode-extension

    tsa:
      config:
        areaPath: "Visual Studio Code Miscellaneous Extensions"
        serviceTreeID: "c8cb03c6-176e-40dd-90a5-518de08666dc"
      enabled: true
